#!/usr/bin/env -S uv run --python 3.12 python
"""Generate bundled mapping module from hogwash release data.

Usage:
  uv run --python 3.12 python analysis/generate_mapping_module.py --latest
  uv run --python 3.12 python analysis/generate_mapping_module.py --tag v0.1.4
  uv run --python 3.12 python analysis/generate_mapping_module.py --from-file /path/to/secret-mapping.gondolin.json
  uv run --python 3.12 python analysis/generate_mapping_module.py --latest --sha256 <expected_sha256>

Output:
- src/generated/secret-mapping.ts
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = "hochej/hogwash"
ASSET = "secret-mapping.gondolin.json"
API_BASE = f"https://api.github.com/repos/{REPO}"
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_TS = REPO_ROOT / "src" / "generated" / "secret-mapping.ts"


def github_headers(*, accept: str = "application/vnd.github+json") -> dict[str, str]:
    headers = {
        "Accept": accept,
        "X-GitHub-Api-Version": "2022-11-28",
        "User-Agent": "envwise-mapping-generator",
    }

    token = os.getenv("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"

    return headers


def request_json(path: str) -> dict:
    url = f"{API_BASE}{path}"
    req = urllib.request.Request(url, headers=github_headers())

    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"GitHub API request failed ({exc.code}) for {url}: {body}") from exc


def resolve_latest_tag() -> str:
    data = request_json("/releases/latest")
    tag = data.get("tag_name")
    if not isinstance(tag, str) or not tag:
        raise SystemExit("GitHub API response missing release tag_name")

    return tag


def resolve_asset_download_url(tag: str) -> str:
    release = request_json(f"/releases/tags/{tag}")
    assets = release.get("assets")

    if not isinstance(assets, list):
        raise SystemExit(f"Release {tag} has no assets array")

    for asset in assets:
        if not isinstance(asset, dict):
            continue
        if asset.get("name") != ASSET:
            continue

        url = asset.get("browser_download_url")
        if isinstance(url, str) and url:
            return url

    raise SystemExit(f"Release {tag} does not contain asset {ASSET}")


def download_text(url: str) -> str:
    req = urllib.request.Request(url, headers=github_headers(accept="application/octet-stream"))

    try:
        with urllib.request.urlopen(req, timeout=60) as response:
            return response.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"Asset download failed ({exc.code}) for {url}: {body}") from exc


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def load_mapping_json(args: argparse.Namespace) -> tuple[str, str]:
    if args.from_file:
        mapping_path = Path(args.from_file)
        if not mapping_path.exists():
            raise SystemExit(f"Mapping file does not exist: {mapping_path}")

        return mapping_path.read_text(encoding="utf-8"), str(mapping_path)

    tag = args.tag or (resolve_latest_tag() if args.latest else None)
    if not tag:
        raise SystemExit("Provide --tag, --latest, or --from-file")

    download_url = resolve_asset_download_url(tag)
    return download_text(download_url), f"hogwash release {tag}"


def write_module(raw_json: str, digest: str) -> None:
    # Validate JSON structure before writing module.
    json.loads(raw_json)

    content = """// AUTO-GENERATED FILE. DO NOT EDIT.
//
// Generated by: analysis/generate_mapping_module.py

import type { SecretMappingData } from "../types.js";

export const SECRET_MAPPING_SHA256 = """ + json.dumps(digest) + """;

export const SECRET_MAPPING_JSON = """ + json.dumps(raw_json) + """;

export const SECRET_MAPPING_DATA: SecretMappingData = JSON.parse(SECRET_MAPPING_JSON) as SecretMappingData;
"""

    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    OUT_TS.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", help="hogwash release tag (e.g. v0.1.4)")
    parser.add_argument("--latest", action="store_true", help="use latest hogwash release")
    parser.add_argument("--from-file", help="path to local secret-mapping.gondolin.json")
    parser.add_argument(
        "--sha256",
        help="optional expected SHA256 for secret-mapping.gondolin.json; aborts on mismatch",
    )
    args = parser.parse_args()

    selected_sources = [bool(args.tag), bool(args.latest), bool(args.from_file)]
    if sum(selected_sources) != 1:
        raise SystemExit("Select exactly one source: --tag, --latest, or --from-file")

    raw_json, source = load_mapping_json(args)

    digest = sha256_bytes(raw_json.encode("utf-8"))
    expected = args.sha256.lower() if args.sha256 else None
    if expected and digest != expected:
        raise SystemExit(
            "Downloaded artifact checksum mismatch: "
            f"expected {expected}, got {digest}"
        )

    write_module(raw_json, digest)

    print(f"wrote {OUT_TS.relative_to(REPO_ROOT)}")
    print(f"source: {source}")
    print(f"sha256: {digest}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(130)
